const characters = [
  {
    id: 1,
    name: "Goku",
    race: "Saiyan",
    gender: "Male",
    originPlanet: "Earth",
    status: "Alive",
  },
  {
    id: 2,
    name: "Vegeta",
    race: "Saiyan",
    gender: "Male",
    originPlanet: "Vegeta",
    status: "Alive",
  },
  {
    id: 3,
    name: "Piccolo",
    race: "Namekian",
    gender: "Male",
    originPlanet: "Namek",
    status: "Alive",
  },
  {
    id: 4,
    name: "Gohan",
    race: "Half-Saiyan",
    gender: "Male",
    originPlanet: "Earth",
    status: "Alive",
  },
  {
    id: 5,
    name: "Frieza",
    race: "Alien",
    gender: "Male",
    originPlanet: "Unknown",
    status: "Alive",
  },
  {
    id: 6,
    name: "Trunks",
    race: "Half-Saiyan",
    gender: "Male",
    originPlanet: "Earth",
    status: "Alive",
  },
  {
    id: 7,
    name: "Krillin",
    race: "Human",
    gender: "Male",
    originPlanet: "Earth",
    status: "Alive",
  },
  {
    id: 8,
    name: "Cell",
    race: "Bio-Android",
    gender: "Male",
    originPlanet: "Earth",
    status: "Dead",
  },
  {
    id: 9,
    name: "Majin Buu",
    race: "Majin",
    gender: "Male",
    originPlanet: "Unknown",
    status: "Alive",
  },
  {
    id: 10,
    name: "Android 18",
    race: "Android",
    gender: "Female",
    originPlanet: "Earth",
    status: "Alive",
  },
];

module.exports = characters;
